// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: wishlist/v1/wishlist.proto

package wishlistv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetWishlistRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetWishlistRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetWishlistRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetWishlistRequestMultiError, or nil if none found.
func (m *GetWishlistRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetWishlistRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetWishlistRequestMultiError(errors)
	}

	return nil
}

// GetWishlistRequestMultiError is an error wrapping multiple validation errors
// returned by GetWishlistRequest.ValidateAll() if the designated constraints
// aren't met.
type GetWishlistRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetWishlistRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetWishlistRequestMultiError) AllErrors() []error { return m }

// GetWishlistRequestValidationError is the validation error returned by
// GetWishlistRequest.Validate if the designated constraints aren't met.
type GetWishlistRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetWishlistRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetWishlistRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetWishlistRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetWishlistRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetWishlistRequestValidationError) ErrorName() string {
	return "GetWishlistRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetWishlistRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetWishlistRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetWishlistRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetWishlistRequestValidationError{}

// Validate checks the field values on GetWishlistResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetWishlistResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetWishlistResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetWishlistResponseMultiError, or nil if none found.
func (m *GetWishlistResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetWishlistResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetWishlistResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetWishlistResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetWishlistResponseValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetWishlistResponseMultiError(errors)
	}

	return nil
}

// GetWishlistResponseMultiError is an error wrapping multiple validation
// errors returned by GetWishlistResponse.ValidateAll() if the designated
// constraints aren't met.
type GetWishlistResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetWishlistResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetWishlistResponseMultiError) AllErrors() []error { return m }

// GetWishlistResponseValidationError is the validation error returned by
// GetWishlistResponse.Validate if the designated constraints aren't met.
type GetWishlistResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetWishlistResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetWishlistResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetWishlistResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetWishlistResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetWishlistResponseValidationError) ErrorName() string {
	return "GetWishlistResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetWishlistResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetWishlistResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetWishlistResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetWishlistResponseValidationError{}

// Validate checks the field values on AddItemRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AddItemRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddItemRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AddItemRequestMultiError,
// or nil if none found.
func (m *AddItemRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AddItemRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ProductId

	if len(errors) > 0 {
		return AddItemRequestMultiError(errors)
	}

	return nil
}

// AddItemRequestMultiError is an error wrapping multiple validation errors
// returned by AddItemRequest.ValidateAll() if the designated constraints
// aren't met.
type AddItemRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddItemRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddItemRequestMultiError) AllErrors() []error { return m }

// AddItemRequestValidationError is the validation error returned by
// AddItemRequest.Validate if the designated constraints aren't met.
type AddItemRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddItemRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddItemRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddItemRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddItemRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddItemRequestValidationError) ErrorName() string { return "AddItemRequestValidationError" }

// Error satisfies the builtin error interface
func (e AddItemRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddItemRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddItemRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddItemRequestValidationError{}

// Validate checks the field values on AddItemResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AddItemResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddItemResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddItemResponseMultiError, or nil if none found.
func (m *AddItemResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AddItemResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetItem()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AddItemResponseValidationError{
					field:  "Item",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AddItemResponseValidationError{
					field:  "Item",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetItem()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AddItemResponseValidationError{
				field:  "Item",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return AddItemResponseMultiError(errors)
	}

	return nil
}

// AddItemResponseMultiError is an error wrapping multiple validation errors
// returned by AddItemResponse.ValidateAll() if the designated constraints
// aren't met.
type AddItemResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddItemResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddItemResponseMultiError) AllErrors() []error { return m }

// AddItemResponseValidationError is the validation error returned by
// AddItemResponse.Validate if the designated constraints aren't met.
type AddItemResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddItemResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddItemResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddItemResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddItemResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddItemResponseValidationError) ErrorName() string { return "AddItemResponseValidationError" }

// Error satisfies the builtin error interface
func (e AddItemResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddItemResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddItemResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddItemResponseValidationError{}

// Validate checks the field values on RemoveItemRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *RemoveItemRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RemoveItemRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RemoveItemRequestMultiError, or nil if none found.
func (m *RemoveItemRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RemoveItemRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ProductId

	if len(errors) > 0 {
		return RemoveItemRequestMultiError(errors)
	}

	return nil
}

// RemoveItemRequestMultiError is an error wrapping multiple validation errors
// returned by RemoveItemRequest.ValidateAll() if the designated constraints
// aren't met.
type RemoveItemRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RemoveItemRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RemoveItemRequestMultiError) AllErrors() []error { return m }

// RemoveItemRequestValidationError is the validation error returned by
// RemoveItemRequest.Validate if the designated constraints aren't met.
type RemoveItemRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RemoveItemRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RemoveItemRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RemoveItemRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RemoveItemRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RemoveItemRequestValidationError) ErrorName() string {
	return "RemoveItemRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RemoveItemRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRemoveItemRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RemoveItemRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RemoveItemRequestValidationError{}

// Validate checks the field values on RemoveItemResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RemoveItemResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RemoveItemResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RemoveItemResponseMultiError, or nil if none found.
func (m *RemoveItemResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *RemoveItemResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	if len(errors) > 0 {
		return RemoveItemResponseMultiError(errors)
	}

	return nil
}

// RemoveItemResponseMultiError is an error wrapping multiple validation errors
// returned by RemoveItemResponse.ValidateAll() if the designated constraints
// aren't met.
type RemoveItemResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RemoveItemResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RemoveItemResponseMultiError) AllErrors() []error { return m }

// RemoveItemResponseValidationError is the validation error returned by
// RemoveItemResponse.Validate if the designated constraints aren't met.
type RemoveItemResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RemoveItemResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RemoveItemResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RemoveItemResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RemoveItemResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RemoveItemResponseValidationError) ErrorName() string {
	return "RemoveItemResponseValidationError"
}

// Error satisfies the builtin error interface
func (e RemoveItemResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRemoveItemResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RemoveItemResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RemoveItemResponseValidationError{}

// Validate checks the field values on InWishlistRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *InWishlistRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on InWishlistRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// InWishlistRequestMultiError, or nil if none found.
func (m *InWishlistRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *InWishlistRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ProductId

	if len(errors) > 0 {
		return InWishlistRequestMultiError(errors)
	}

	return nil
}

// InWishlistRequestMultiError is an error wrapping multiple validation errors
// returned by InWishlistRequest.ValidateAll() if the designated constraints
// aren't met.
type InWishlistRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m InWishlistRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m InWishlistRequestMultiError) AllErrors() []error { return m }

// InWishlistRequestValidationError is the validation error returned by
// InWishlistRequest.Validate if the designated constraints aren't met.
type InWishlistRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e InWishlistRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e InWishlistRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e InWishlistRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e InWishlistRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e InWishlistRequestValidationError) ErrorName() string {
	return "InWishlistRequestValidationError"
}

// Error satisfies the builtin error interface
func (e InWishlistRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sInWishlistRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = InWishlistRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = InWishlistRequestValidationError{}

// Validate checks the field values on InWishlistResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *InWishlistResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on InWishlistResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// InWishlistResponseMultiError, or nil if none found.
func (m *InWishlistResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *InWishlistResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for InWishlist

	if len(errors) > 0 {
		return InWishlistResponseMultiError(errors)
	}

	return nil
}

// InWishlistResponseMultiError is an error wrapping multiple validation errors
// returned by InWishlistResponse.ValidateAll() if the designated constraints
// aren't met.
type InWishlistResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m InWishlistResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m InWishlistResponseMultiError) AllErrors() []error { return m }

// InWishlistResponseValidationError is the validation error returned by
// InWishlistResponse.Validate if the designated constraints aren't met.
type InWishlistResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e InWishlistResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e InWishlistResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e InWishlistResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e InWishlistResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e InWishlistResponseValidationError) ErrorName() string {
	return "InWishlistResponseValidationError"
}

// Error satisfies the builtin error interface
func (e InWishlistResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sInWishlistResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = InWishlistResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = InWishlistResponseValidationError{}

// Validate checks the field values on WishlistItem with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *WishlistItem) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WishlistItem with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in WishlistItemMultiError, or
// nil if none found.
func (m *WishlistItem) ValidateAll() error {
	return m.validate(true)
}

func (m *WishlistItem) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for ProductId

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, WishlistItemValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, WishlistItemValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return WishlistItemValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return WishlistItemMultiError(errors)
	}

	return nil
}

// WishlistItemMultiError is an error wrapping multiple validation errors
// returned by WishlistItem.ValidateAll() if the designated constraints aren't met.
type WishlistItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WishlistItemMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WishlistItemMultiError) AllErrors() []error { return m }

// WishlistItemValidationError is the validation error returned by
// WishlistItem.Validate if the designated constraints aren't met.
type WishlistItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WishlistItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WishlistItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WishlistItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WishlistItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WishlistItemValidationError) ErrorName() string { return "WishlistItemValidationError" }

// Error satisfies the builtin error interface
func (e WishlistItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWishlistItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WishlistItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WishlistItemValidationError{}
