// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: balance/v1/balance.proto

package balancev1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetBalanceRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetBalanceRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetBalanceRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetBalanceRequestMultiError, or nil if none found.
func (m *GetBalanceRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetBalanceRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetBalanceRequestMultiError(errors)
	}

	return nil
}

// GetBalanceRequestMultiError is an error wrapping multiple validation errors
// returned by GetBalanceRequest.ValidateAll() if the designated constraints
// aren't met.
type GetBalanceRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetBalanceRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetBalanceRequestMultiError) AllErrors() []error { return m }

// GetBalanceRequestValidationError is the validation error returned by
// GetBalanceRequest.Validate if the designated constraints aren't met.
type GetBalanceRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetBalanceRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetBalanceRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetBalanceRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetBalanceRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetBalanceRequestValidationError) ErrorName() string {
	return "GetBalanceRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetBalanceRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetBalanceRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetBalanceRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetBalanceRequestValidationError{}

// Validate checks the field values on GetBalanceResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetBalanceResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetBalanceResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetBalanceResponseMultiError, or nil if none found.
func (m *GetBalanceResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetBalanceResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Amount

	if len(errors) > 0 {
		return GetBalanceResponseMultiError(errors)
	}

	return nil
}

// GetBalanceResponseMultiError is an error wrapping multiple validation errors
// returned by GetBalanceResponse.ValidateAll() if the designated constraints
// aren't met.
type GetBalanceResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetBalanceResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetBalanceResponseMultiError) AllErrors() []error { return m }

// GetBalanceResponseValidationError is the validation error returned by
// GetBalanceResponse.Validate if the designated constraints aren't met.
type GetBalanceResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetBalanceResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetBalanceResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetBalanceResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetBalanceResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetBalanceResponseValidationError) ErrorName() string {
	return "GetBalanceResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetBalanceResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetBalanceResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetBalanceResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetBalanceResponseValidationError{}

// Validate checks the field values on DepositRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DepositRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DepositRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DepositRequestMultiError,
// or nil if none found.
func (m *DepositRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DepositRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Amount

	// no validation rules for Comment

	if len(errors) > 0 {
		return DepositRequestMultiError(errors)
	}

	return nil
}

// DepositRequestMultiError is an error wrapping multiple validation errors
// returned by DepositRequest.ValidateAll() if the designated constraints
// aren't met.
type DepositRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DepositRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DepositRequestMultiError) AllErrors() []error { return m }

// DepositRequestValidationError is the validation error returned by
// DepositRequest.Validate if the designated constraints aren't met.
type DepositRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DepositRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DepositRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DepositRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DepositRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DepositRequestValidationError) ErrorName() string { return "DepositRequestValidationError" }

// Error satisfies the builtin error interface
func (e DepositRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDepositRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DepositRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DepositRequestValidationError{}

// Validate checks the field values on DepositResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DepositResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DepositResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DepositResponseMultiError, or nil if none found.
func (m *DepositResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DepositResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Amount

	if len(errors) > 0 {
		return DepositResponseMultiError(errors)
	}

	return nil
}

// DepositResponseMultiError is an error wrapping multiple validation errors
// returned by DepositResponse.ValidateAll() if the designated constraints
// aren't met.
type DepositResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DepositResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DepositResponseMultiError) AllErrors() []error { return m }

// DepositResponseValidationError is the validation error returned by
// DepositResponse.Validate if the designated constraints aren't met.
type DepositResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DepositResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DepositResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DepositResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DepositResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DepositResponseValidationError) ErrorName() string { return "DepositResponseValidationError" }

// Error satisfies the builtin error interface
func (e DepositResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDepositResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DepositResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DepositResponseValidationError{}

// Validate checks the field values on GetTransactionHistoryRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetTransactionHistoryRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTransactionHistoryRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetTransactionHistoryRequestMultiError, or nil if none found.
func (m *GetTransactionHistoryRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTransactionHistoryRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Limit

	// no validation rules for Offset

	if len(errors) > 0 {
		return GetTransactionHistoryRequestMultiError(errors)
	}

	return nil
}

// GetTransactionHistoryRequestMultiError is an error wrapping multiple
// validation errors returned by GetTransactionHistoryRequest.ValidateAll() if
// the designated constraints aren't met.
type GetTransactionHistoryRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTransactionHistoryRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTransactionHistoryRequestMultiError) AllErrors() []error { return m }

// GetTransactionHistoryRequestValidationError is the validation error returned
// by GetTransactionHistoryRequest.Validate if the designated constraints
// aren't met.
type GetTransactionHistoryRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTransactionHistoryRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTransactionHistoryRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTransactionHistoryRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTransactionHistoryRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTransactionHistoryRequestValidationError) ErrorName() string {
	return "GetTransactionHistoryRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetTransactionHistoryRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTransactionHistoryRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTransactionHistoryRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTransactionHistoryRequestValidationError{}

// Validate checks the field values on GetTransactionHistoryResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetTransactionHistoryResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTransactionHistoryResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// GetTransactionHistoryResponseMultiError, or nil if none found.
func (m *GetTransactionHistoryResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTransactionHistoryResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetTransactions() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetTransactionHistoryResponseValidationError{
						field:  fmt.Sprintf("Transactions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetTransactionHistoryResponseValidationError{
						field:  fmt.Sprintf("Transactions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetTransactionHistoryResponseValidationError{
					field:  fmt.Sprintf("Transactions[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	if len(errors) > 0 {
		return GetTransactionHistoryResponseMultiError(errors)
	}

	return nil
}

// GetTransactionHistoryResponseMultiError is an error wrapping multiple
// validation errors returned by GetTransactionHistoryResponse.ValidateAll()
// if the designated constraints aren't met.
type GetTransactionHistoryResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTransactionHistoryResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTransactionHistoryResponseMultiError) AllErrors() []error { return m }

// GetTransactionHistoryResponseValidationError is the validation error
// returned by GetTransactionHistoryResponse.Validate if the designated
// constraints aren't met.
type GetTransactionHistoryResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTransactionHistoryResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTransactionHistoryResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTransactionHistoryResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTransactionHistoryResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTransactionHistoryResponseValidationError) ErrorName() string {
	return "GetTransactionHistoryResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetTransactionHistoryResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTransactionHistoryResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTransactionHistoryResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTransactionHistoryResponseValidationError{}

// Validate checks the field values on BalanceTransaction with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *BalanceTransaction) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BalanceTransaction with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BalanceTransactionMultiError, or nil if none found.
func (m *BalanceTransaction) ValidateAll() error {
	return m.validate(true)
}

func (m *BalanceTransaction) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Type

	// no validation rules for Amount

	// no validation rules for Comment

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BalanceTransactionValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BalanceTransactionValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BalanceTransactionValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return BalanceTransactionMultiError(errors)
	}

	return nil
}

// BalanceTransactionMultiError is an error wrapping multiple validation errors
// returned by BalanceTransaction.ValidateAll() if the designated constraints
// aren't met.
type BalanceTransactionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BalanceTransactionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BalanceTransactionMultiError) AllErrors() []error { return m }

// BalanceTransactionValidationError is the validation error returned by
// BalanceTransaction.Validate if the designated constraints aren't met.
type BalanceTransactionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BalanceTransactionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BalanceTransactionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BalanceTransactionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BalanceTransactionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BalanceTransactionValidationError) ErrorName() string {
	return "BalanceTransactionValidationError"
}

// Error satisfies the builtin error interface
func (e BalanceTransactionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBalanceTransaction.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BalanceTransactionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BalanceTransactionValidationError{}
